/*
 * ICU common data table of contents for xercesc_messages_3_1.dat
 * Automatically generated by icu/source/tools/gencmn/gencmn .
 */

#include "unicode/utypes.h"
#include "unicode/udata.h"

/* external symbol declarations for data (1 files) */
extern const char
    xercesc_messages_3_1_root_res[];

U_EXPORT struct {
    uint16_t headerSize;
    uint8_t magic1, magic2;
    UDataInfo info;
    char padding[8];
    uint32_t count, reserved;
    struct {
        const char *name;
        const void *data;
    } toc[1];
} U_EXPORT2 xercesc_messages_3_1_dat = {
    32, 0xda, 0x27, {
        20, 0,
        0, 0, 2, 0,
        {0x54, 0x6f, 0x43, 0x50},
        {1, 0, 0, 0},
        {0, 0, 0, 0}
    },
    "", 1, 0, {
        { "xercesc_messages_3_1/root.res", xercesc_messages_3_1_root_res }
    }
};
